openapi: 3.0.1
info:
  title: Bff Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /greeting:
    get:
      operationId: getGreeting
      parameters:
      - name: subpath
        in: query
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "202":
          description: Accepted
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /diagnostic:
    get:
      operationId: getDiagnostic
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
