openapi: 3.0.1
info:
  title: Echo
  version: 0.1.0
servers:
- url: "{server}:{port}/echo"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /diagnostic:
    get:
      operationId: getDiagnostic
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
  /hello:
    get:
      operationId: getHello
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
